services:
  nginx:
    image: nginx:1.27-alpine3.21
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - ".:/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  phpfpm:
    build:
      context: "./docker/phpFPM"
      dockerfile: phpFPM.Dockerfile
    volumes:
      - ".:/app"
      - "./docker/phpFPM/php.ini:/usr/local/etc/php/php.ini"
  db:
    image: postgres:17-alpine3.21
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root1234"
